version: '3.8'

services:
  back:
    entrypoint: ["npm"]
    command: ["start"]
    image: amaysim/serverless:3.30.1
    container_name: back
    expose:
      - 3000
    ports:
      - "3000:3001"
    networks:
      default:
    env_file:
      - "./_docker/.env"
    environment:
      - NODE_ENV=development
    volumes:
      - "./back/:/opt/app:delegated"
  front:
    entrypoint: ["npm"]
    command: ["run", "dev"]
    image: amaysim/serverless:3.30.1
    container_name: front
    expose:
      - 8080
    ports:
      - "8080:3000"
    networks:
      default:
    environment:
      - NODE_ENV=development
    volumes:
      - "./front/:/opt/app:delegated"
networks:
  default:
